### ISSUE TITLE
在linux上编译AlgoPlus.CTP.TraderApiBase会报错gcc: fatal error: Killed signal terminated program as compilation terminated. error: command '/usr/bin/gcc' failed with exit code 1

### ISSUE THREAD

**Issue by ghost** [CTPPlus/AlgoPlus#14]
<img width="773" alt="1655571822894" src="https://user-images.githubusercontent.com/61618296/174449104-baa02c1d-67df-4cc5-9ab0-2dcd1208ca33.png">

**Comment by yinlinzhan** [comment]
> <img alt="1655571822894" width="773" src="https://user-images.githubusercontent.com/61618296/174449104-baa02c1d-67df-4cc5-9ab0-2dcd1208ca33.png">
