### ISSUE TITLE
有么有什么办法可以切换CTP的版本?

### ISSUE THREAD

**Issue by keybatman** [CTPPlus/AlgoPlus#5]
目前期货公司正式生产通常是CTP v6.3.15版，
而测试账号通常使用v6.3.13。

进行客户端认证时, 通常先要通过测试.  所以,

请问有么有什么办法可以切换CTP版本? 谢谢
AlgoPlus 是通过 `pip install AlgoPlus` 安装的

**Comment by CTPPlus** [comment]
不再往前兼容了，会往后兼容。

**Comment by keybatman** [comment]
好的, 谢谢!
