### ISSUE TITLE
你好，请问下如果我想得到类似成交的明细数据应该怎么做

### ISSUE THREAD

**Issue by obrua** [CTPPlus/AlgoPlus#7]
不是个人的成交明细，是指说行情的实时交易明细
请教一下~

**Comment by CTPPlus** [comment]
最小的行情单位就是MdApi在OnRtnDepthMarketData中收到的行情切片，一般500ms一次，没有你想要的明细

**Comment by obrua** [comment]
自己算了只能 谢谢
